=== James-REANNZ/psconfig/doc/psconfig-maddash-check-plugin-schema.json
{
    "id": "http://www.perfsonar.net/psconfig-maddash-agent-check-plugin-schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "pSConfig MaDDash Check Plug-In Schema",
    "description": "Schema for pSConfig MaDDash Check Plug-ins. This allows people to define new types of checks",
    "type": "object",
    "additionalProperties": false,
    "required": [ "type", "name", "description", "requires", "status-labels", "defaults", "command" ],
    "properties": {
    
        "type": {
            "type": "string",
            "description": "Type of check. Used by other config files to reference this check."
        }, 
        
        "name": {
            "type": "string",
            "description": "Human-readable name used for display purposes"
        },
        
        "description": {
            "type": "string",
            "description": "Human-readable description used for display purposes that tells what check does"
        },
        
        "requires": {
            "$ref": "#/pSConfig/TaskSelector",
            "description": "Indicates minimum requirements a task must meet to use this task"
        },
        
        "archive-accessor": {
            "$ref": "#/pSConfig/JQTransformSpecification",
            "description": "JQ script used to build the accessor for supported archivers"
        },
        
        "status-labels": {
            "$ref": "#/pSConfig/StatusLabels",
            "description": "Descriptions of what each status level means"
        },
        
        "defaults": {
            "$ref": "#/pSConfig/CheckDefaults",
            "description": "Default parameters for plug-in"
        },
        
        "vars": {
            "$ref": "#/pSConfig/CheckVars",
            "description": "Custom variables that can be used in command-opts, command-args and maddash-check-params in format {% var.VARNAME %}"
        },
        
        "command": {
            "type": "string",
            "description": "The command to run for this check. Can use variables like {% check_opts %} and {% check_args %} to build checks."
        },
        
        "command-opts": {
            "$ref": "#/pSConfig/CommandOpts",
            "description": "A list of command line options to be used with check. Keys must start with - the value is an object defining when and how to use check"
        },
        
        "command-args": {
            "type": "array",
            "items": { "type": "string" } ,
            "description": "List of arguments to pass to the command-line"
        }
    },
    
     "pSConfig": {
        
        "AnyJSON": {
            "anyOf": [
                { "type": "array" },
                { "type": "boolean" },
                { "type": "integer" },
                { "type": "null" },
                { "type": "number" },
                { "type": "object" },
                { "type": "string" }
            ]
        },
        
        "CheckDefaults": {
            "type": "object",
            "properties": {
                "check-interval": {
                    "$ref": "#/pSConfig/Duration",
                    "description": "How often to run check"
                },
                "warning-threshold": {
                    "type": "string",
                    "description": "Threshold for warning level"
                },
                "critical-threshold": {
                    "type": "string",
                    "description": "Threshold for critical level"
                },
                "report-yaml-file": {
                    "type": "string",
                    "description": "Location of YAML file with report to use for this check"
                },
                "retry-interval": {
                    "$ref": "#/pSConfig/Duration",
                    "description": "How often to check after a check detects a change in state"
                },
                "retry-attempts": {
                    "$ref": "#/pSConfig/IntZero",
                    "description": "How many times to retry after detecting a change in state"
                },
                "timeout": {
                    "$ref": "#/pSConfig/Duration",
                    "description": "How long to wait for check to complete"
                },
                "params": {
                    "$ref": "#/pSConfig/AnyJSON",
                    "description": "Plug-in specific parameters"
                }
            },
            "required": [ "check-interval", "critical-threshold", "warning-threshold" ],
            "additionalProperties": false
        },
        
        "CheckVars": {
            "type": "object",
            "patternProperties": { 
                "^[a-zA-Z0-9:._\\-]+$": { "$ref": "#/pSConfig/JQTransformSpecification" }
            },
            "additionalProperties": false
        },
        
        "CommandOpt": {
            "type": "object",
            "properties": { 
                "condition": {
                    "type": "string",
                    "description": "String that must be non-empty string for this condition to evaluate true. Use variables here to make truly conditional."
                },
                "arg": {
                    "type": "string",
                    "description": "Argument to pass to option. Use variables here to set dynamic values."
                },
                "required": {
                    "type": "boolean",
                    "description": "Indicates whether option is required to run"
                } 
            },
            "required": [ "condition" ],
            "additionalProperties": false
        },
        
        "CommandOpts": {
            "type": "object",
            "patternProperties": { 
                "^-[a-zA-Z0-9:._\\-]+$": { "$ref": "#/pSConfig/CommandOpt" }
            },
            "additionalProperties": false
        },
        
        "Duration": {
            "type": "string",
            "pattern": "^P(?:\\d+(?:\\.\\d+)?W)?(?:\\d+(?:\\.\\d+)?D)?(?:T(?:\\d+(?:\\.\\d+)?H)?(?:\\d+(?:\\.\\d+)?M)?(?:\\d+(?:\\.\\d+)?S)?)?$",
            "x-invalid-message": "'%s' is not a valid ISO 8601 duration."
        },
        
        "JQTransformSpecification": {
            "type": "object",
            "properties": {
                "script":   {
                    "anyOf": [
                        { "type": "string" },
                        { "type": "array", "items": { "type": "string" } }
                    ]
                }
            },
            "additionalProperties": false,
            "required": [ "script" ]
        },
        
        "IntZero": {
            "type": "integer",
            "minimum": 0
        },

        "StatusLabels": {
            "type": "object",
            "properties": {
                "ok": { "type": "string" },
                "warning": { "type": "string" },
                "critical": { "type": "string" },
                "notrun": { "type": "string" },
                "unknown": { "type": "string" },
                "custom": { 
                    "$ref": "#/pSConfig/StatusLabelCustom" 
                }
            },
            "required": [ "ok", "warning", "critical", "notrun", "unknown"],
            "additionalProperties": false
        },
        
        "StatusLabelCustom": {
            "type": "object",
            "patternProperties": { 
                "^[0-9]+$": { "type": "string" }
            },
            "additionalProperties": false
        },
        
        "TaskSelector": {
            "type": "object",
            "properties": {
                "test-type": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Match against any test-type in the list"
                },
                "task-name": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Match against any task name in the list"
                },
                "archive-type": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Match against any archiver with the given type"
                },
                "jq": { 
                    "$ref": "#/pSConfig/JQTransformSpecification",
                    "description": "JQ script to transform downloaded pSConfig JSON"
                    
                }
            },
            "additionalProperties": false
        }
    }
}

=== James-REANNZ/psconfig/plugins/checks/ps-nagios-http.json
{
    "type": "ps-nagios-http",
    "name": "HTTP",
    "description": "Queries an esmond MA for HTTP tests and alarms on time reported by test by default (can look at other parameters using the jq option)",
    "requires": {
        "test-type": ["http"],
        "archive-type": ["esmond"]
    },
    "archive-accessor": {
        "script": [ ".url" ]
    },
    "status-labels": {
        "ok": "Value {% check.params.label-ok-symbol %} {% check.warning %}{% check.params.units %}",
        "warning": "Value {% label-warning-symbol %} {% check.params.units %}",
        "critical": "Value {% label-critical-symbol %} {% check.params.units %}",
        "notrun": "Check has not run yet",
        "unknown": "Unable to find test data"
    },
    "defaults": {
        "check-interval": "PT1H",
        "warning-threshold": "1",
        "critical-threshold": "2",
        "retry-attempts": 1,
        "retry-interval": "PT15M",
        "report-yaml-file": "",
        "timeout": "PT60S",
        "params": {
            "time-range": "86400",
            "tool": "",
            "event-type": "pscheduler-raw",
            "function": "",
            "jq": ".time",
            "units": "s",
            "label-ok-symbol": "<",
            "label-warning-symbol": ">=",
            "label-critical-symbol": ">="
        }
    },
    "vars": {
        "test_url": { 
            "script": [
                ".test.spec.url"
            ]
        }
    },
    "command": "/usr/lib64/nagios/plugins/check_esmond",
    "command-opts": {
        "--url": {
            "required": true,
            "condition": "{% ma_url_forward %}",
            "arg": "{% ma_url_forward %}"
        },
        "--event-type": {
            "condition": "{% check.params.event-type %}",
            "arg": "{% check.params.event-type %}"
        },
        "--measurement-agent": {
            "condition": "{% row %}",
            "arg": "{% row %}"
        },
        "--function": {
            "condition": "{% check.params.function %}",
            "arg": "{% check.params.function %}"
        },
        "--jq": {
            "condition": "{% check.params.jq %}",
            "arg": "{% check.params.jq %}"
        },
        "--time-range": {
            "required": true,
            "condition": "{% check.params.time-range %}",
            "arg": "{% check.params.time-range %}"
        },
        "--warning": {
            "required": true,
            "condition": "{% check.warning %}",
            "arg": "{% check.warning %}"
        },
        "--critical": {
            "required": true,
            "condition": "{% check.critical %}",
            "arg": "{% check.critical %}"
        },
        "--tool-name": {
            "condition": "{% check.params.tool %}",
            "arg": "{% check.params.tool %}"
        },
        "--timeout": {
            "condition": "{% check.timeout.seconds %}",
            "arg": "{% check.timeout.seconds %}"
        },
        "--metadata-params": {
            "condition": "{% check.vars.test_url %}",
            "arg": "pscheduler-http-url={% check.vars.test_url %}"
        }
    }
}

=== James-REANNZ/psconfig/psconfig/perfsonar-psconfig/plugins/checks/ps-nagios-dns.json
{
    "type": "ps-nagios-dns",
    "name": "DNS",
    "description": "Queries an esmond MA for HTTP tests and alarms on time reported by test by default (can look at other parameters using the jq option)",
    "requires": {
        "test-type": ["dns"],
        "archive-type": ["esmond", "http"]
    },
    "archive-accessor": {
        "script": [ 
            ". | if (._meta.esmond_url != null) then ",
            "   ._meta.esmond_url ",
            "else ",
            "   .data.url ",
            "end"
        ]
    },
    "status-labels": {
        "ok": "Value {% check.params.label-ok-symbol %} {% check.warning %}{% check.params.units %}",
        "warning": "Value {% check.params.label-warning-symbol %} {% check.warning %}{% check.params.units %}",
        "critical": "Value {% check.params.label-critical-symbol %} {% check.critical %}{% check.params.units %}",
        "notrun": "Check has not run yet",
        "unknown": "Unable to find test data"
    },
    "defaults": {
        "check-interval": "PT1H",
        "warning-threshold": "1",
        "critical-threshold": "2",
        "retry-attempts": 1,
        "retry-interval": "PT15M",
        "report-yaml-file": "",
        "timeout": "PT60S",
        "params": {
            "time-range": "86400",
            "tool": "",
            "function": "",
            "jq": ".time",
            "use-host": "",
            "units": "s",
            "scale": "",
            "label-ok-symbol": "<",
            "label-warning-symbol": ">=",
            "label-critical-symbol": ">="
        }
    },
    "vars": {
        "host": { 
            "script": [
                ".test.spec.host"
            ]
        },
        "record": { 
            "script": [
                ".test.spec.record"
            ]
        },
        "query": { 
            "script": [
                ".test.spec.query"
            ]
        },
        "nameserver": { 
            "script": [
                ".test.spec.nameserver"
            ]
        }
    },
    "command": "/usr/lib64/nagios/plugins/check_esmond",
    "command-opts": {
        "--url": {
            "required": true,
            "condition": "{% ma_url_forward %}",
            "arg": "{% ma_url_forward %}"
        },
        "--event-type": {
            "condition": "1",
            "arg": "pscheduler-raw"
        },
        "--metadata-params__type": {
            "condition": "1",
            "arg": "pscheduler-test-type dns"
        },
        "--measurement-agent": {
            "condition": "{% row %}",
            "arg": "{% row %}"
        },
        "--metadata-params__record": {
            "condition": "{% check.vars.record %}",
            "arg": "pscheduler-dns-record {% check.vars.record %}"
        },
        "--metadata-params__query": {
            "condition": "{% check.vars.query %}",
            "arg": "pscheduler-dns-query {% check.vars.query %}"
        },
        "--metadata-params__nameserver": {
            "condition": "{% check.vars.nameserver %}",
            "arg": "pscheduler-dns-nameserver {% check.vars.nameserver %}"
        },
        "--metadata-params__host": {
            "condition": "{% check.params.use-host %}",
            "arg": "pscheduler-dns-host {% check.vars.host %}"
        },
        "--function": {
            "condition": "{% check.params.function %}",
            "arg": "{% check.params.function %}"
        },
        "--jq": {
            "condition": "{% check.params.jq %}",
            "arg": "{% check.params.jq %}"
        },
        "--time-range": {
            "required": true,
            "condition": "{% check.params.time-range %}",
            "arg": "{% check.params.time-range %}"
        },
        "--warning": {
            "required": true,
            "condition": "{% check.warning %}",
            "arg": "{% check.warning %}"
        },
        "--critical": {
            "required": true,
            "condition": "{% check.critical %}",
            "arg": "{% check.critical %}"
        },
        "--tool-name": {
            "condition": "{% check.params.tool %}",
            "arg": "{% check.params.tool %}"
        },
        "--timeout": {
            "condition": "{% check.timeout.seconds %}",
            "arg": "{% check.timeout.seconds %}"
        },
        "--units": {
            "condition": "{% check.params.units %}",
            "arg": "{% check.params.units %}"
        },
        "--scale": {
            "condition": "{% check.params.scale %}",
            "arg": "{% check.params.scale %}"
        }        
    }
}

=== James-REANNZ/psconfig/psconfig/perfsonar-psconfig/plugins/checks/ps-nagios-http.json
{
    "type": "ps-nagios-http",
    "name": "HTTP",
    "description": "Queries an esmond MA for HTTP tests and alarms on time reported by test by default (can look at other parameters using the jq option)",
    "requires": {
        "test-type": ["http"],
        "archive-type": ["esmond", "http"]
    },
    "archive-accessor": {
        "script": [ 
            ". | if (._meta.esmond_url != null) then ",
            "   ._meta.esmond_url ",
            "else ",
            "   .url ",
            "end"
        ]
    },
    "status-labels": {
        "ok": "Value {% check.params.label-ok-symbol %} {% check.warning %}{% check.params.units %}",
        "warning": "Value {% check.params.label-warning-symbol %} {% check.warning %}{% check.params.units %}",
        "critical": "Value {% check.params.label-critical-symbol %} {% check.critical %}{% check.params.units %}",
        "notrun": "Check has not run yet",
        "unknown": "Unable to find test data"
    },
    "defaults": {
        "check-interval": "PT1H",
        "warning-threshold": "1",
        "critical-threshold": "2",
        "retry-attempts": 1,
        "retry-interval": "PT15M",
        "report-yaml-file": "",
        "timeout": "PT60S",
        "params": {
            "time-range": "86400",
            "tool": "",
            "function": "",
            "jq": ".time",
            "use-parse": "",
            "use-host": "",
            "units": "s",
            "scale": "",
            "label-ok-symbol": "<",
            "label-warning-symbol": ">=",
            "label-critical-symbol": ">="
        }
    },
    "vars": {
        "test_url": { 
            "script": [
                ".test.spec.url"
            ]
        },
        "parse": { 
            "script": [
                ".test.spec.parse"
            ]
        },
        "host": { 
            "script": [
                ".test.spec.host"
            ]
        }
    },
    "command": "/usr/lib64/nagios/plugins/check_esmond",
    "command-opts": {
        "--url": {
            "required": true,
            "condition": "{% ma_url_forward %}",
            "arg": "{% ma_url_forward %}"
        },
        "--event-type": {
            "condition": "1",
            "arg": "pscheduler-raw"
        },
        "--metadata-params__type": {
            "condition": "1",
            "arg": "pscheduler-test-type http"
        },
        "--measurement-agent": {
            "condition": "{% row %}",
            "arg": "{% row %}"
        },
        "--metadata-params__url": {
            "condition": "{% check.vars.test_url %}",
            "arg": "pscheduler-http-url {% check.vars.test_url %}"
        },
        "--metadata-params__parse": {
            "condition": "{% check.params.use-parse %}",
            "arg": "pscheduler-http-parse {% check.vars.parse %}"
        },
        "--metadata-params": {
            "condition": "{% check.params.use-host %}",
            "arg": "pscheduler-http-host {% check.vars.host %}"
        },
        "--function": {
            "condition": "{% check.params.function %}",
            "arg": "{% check.params.function %}"
        },
        "--jq": {
            "condition": "{% check.params.jq %}",
            "arg": "{% check.params.jq %}"
        },
        "--time-range": {
            "required": true,
            "condition": "{% check.params.time-range %}",
            "arg": "{% check.params.time-range %}"
        },
        "--warning": {
            "required": true,
            "condition": "{% check.warning %}",
            "arg": "{% check.warning %}"
        },
        "--critical": {
            "required": true,
            "condition": "{% check.critical %}",
            "arg": "{% check.critical %}"
        },
        "--tool-name": {
            "condition": "{% check.params.tool %}",
            "arg": "{% check.params.tool %}"
        },
        "--timeout": {
            "condition": "{% check.timeout.seconds %}",
            "arg": "{% check.timeout.seconds %}"
        },
        "--units": {
            "condition": "{% check.params.units %}",
            "arg": "{% check.params.units %}"
        },
        "--scale": {
            "condition": "{% check.params.scale %}",
            "arg": "{% check.params.scale %}"
        }        
    }
}
